### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ice1x** [isislovecruft/pyrsync#11]
```
# pip install pyrsync
Collecting pyrsync
  Downloading pyrsync-0.1.0.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9uogw_rn/pyrsync_be55c77e6bce4db4845567ddb6731627/setup.py", line 29, in <module>
          long_description=read('README.md'),
        File "/tmp/pip-install-9uogw_rn/pyrsync_be55c77e6bce4db4845567ddb6731627/setup.py", line 24, in read
          return open(os.path.join(os.path.dirname(__file__), fname)).read()
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-9uogw_rn/pyrsync_be55c77e6bce4db4845567ddb6731627/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bruceyongli** [comment]
You’ll need to run this on your machine:
```
python -m pip install setuptools wheel cython cffi
git clone https://github.com/synodriver/pyrsync
cd pyrsync
git submodule update --init --recursive
cd dep
cmake .
cd ..
python setup.py bdist_wheel --use-cython --use-cffi
pip install dist/python_rsync-0.1.1-cp310-cp310-macosx_13_0_arm64.whl
```

Possibly need to install cmake which can be done with `brew install cmake`

**Comment by YisusChrist** [comment]
Hello @ice1x!

Some time ago I made my own version of this project which is compatible with the latest python versions. I highly recommend you to take a look at it if you want to give it a try, because this original project seems to be dead. I don't plan to extend the original project functionality nor add features, my only aim to provide a new version updated to modern times...

You can check it out at https://github.com/YisusChrist/pyrsync2
