### ISSUE TITLE
README.md not included with release to pypi

### ISSUE THREAD

**Issue by riotopsys** [isislovecruft/pyrsync#3]
pip install pyrsync
Downloading/unpacking pyrsync
  Downloading pyrsync-0.1.0.tar.gz
  Running setup.py egg_info for package pyrsync
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/adam.fitzgerald/src/blip/env/build/pyrsync/setup.py", line 29, in <module>
        long_description=read('README.md'),
      File "/Users/adam.fitzgerald/src/blip/env/build/pyrsync/setup.py", line 24, in read
        return open(os.path.join(os.path.dirname(**file**), fname)).read()
    IOError: [Errno 2] No such file or directory: '/Users/adam.fitzgerald/src/blip/env/build/pyrsync/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/adam.fitzgerald/src/blip/env/build/pyrsync/setup.py", line 29, in <module>

```
long_description=read('README.md'),
```

  File "/Users/adam.fitzgerald/src/blip/env/build/pyrsync/setup.py", line 24, in read

```
return open(os.path.join(os.path.dirname(__file__), fname)).read()
```

IOError: [Errno 2] No such file or directory: '/Users/adam.fitzgerald/src/blip/env/build/pyrsync/README.md'

---

Command python setup.py egg_info failed with error code 1 in /Users/adam.fitzgerald/src/blip/env/build/pyrsync
Storing complete log in /Users/adam.fitzgerald/.pip/pip.log

**Comment by pyjl** [comment]
+1 for this issue

**Comment by itsmonktastic** [comment]
Yeah, kind of inconvenient. Workaround if you want to use this library in a requirements file:

pip install -egit+https://github.com/isislovecruft/pyrsync#egg=pyrsync

**Comment by pyjl** [comment]
meh, I just git clone, setup.py instead.

**Comment by itsmonktastic** [comment]
Sure, but the workaround above is useful for any deployments that use pip for pulling down dependencies.

**Comment by jwmatthews** [comment]
@itsmonktastic useful tip, thanks for sharing
